package cn.javass.spring.chapter8;

import java.sql.SQLException;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import cn.javass.spring.chapter7.UserModel;
import cn.javass.spring.chapter7.dao.IUserDao;


public class JPATest {
    
    private static EntityManagerFactory entityManagerFactory;
    private static ApplicationContext ctx;
    
    @BeforeClass
    public static void setUpClass() {
        String[] configLocations = new String[] {
                "classpath:chapter7/applicationContext-resources.xml",
                "classpath:chapter8/applicationContext-jpa.xml"};
        ctx = new ClassPathXmlApplicationContext(configLocations);
        entityManagerFactory = ctx.getBean(EntityManagerFactory.class);
    }

    @Before
    public void setUp() throws SQLException {
        //id自增主键从0开始
        String createTableSql = "create memory table test" +
        "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
        "name varchar(100))";
        executeSql(createTableSql);
    }
    @After
    public void tearDown() throws SQLException {
        String dropTableSql = "drop table test";
        executeSql(dropTableSql);
    }
    
    private void executeSql(String sql) throws SQLException {
        EntityManager em = entityManagerFactory.createEntityManager();
        beginTransaction(em);
        em.createNativeQuery(sql).executeUpdate();
        commitTransaction(em);
        closeEntityManager(em);
    }

    @Test
    public void testFirst() throws SQLException {
        UserModel2 model = new UserModel2();
        model.setMyName("test");
        EntityManager em = null;
        try {
            em = entityManagerFactory.createEntityManager();
            beginTransaction(em);
            em.persist(model);
            commitTransaction(em);
        } catch (RuntimeException e) {
            rollbackTransacrion(em);
            throw e;
        }
        finally {
          closeEntityManager(em);
        }
    }
    
     
    
    @Test
    public void bestPracticeTest() {
        String[] configLocations = new String[] {
                "classpath:chapter7/applicationContext-resources.xml",
                "classpath:chapter8/applicationContext-jpa.xml"};
        ApplicationContext ctx = new ClassPathXmlApplicationContext(configLocations);
        IUserDao userDao = ctx.getBean(IUserDao.class);
        UserModel model = new UserModel();
        model.setMyName("test");
        userDao.save(model);
        Assert.assertEquals(1, userDao.countAll());
    }
    
    
    private void closeEntityManager(EntityManager em) {
        em.close();
    }

    private void rollbackTransacrion(EntityManager em) throws SQLException {
        if(em != null) {
            em.getTransaction().rollback();
        }         
    }

    private void commitTransaction(EntityManager em) throws SQLException {
        em.getTransaction().commit();
    }

    private void beginTransaction(EntityManager em) throws SQLException {
        em.getTransaction().begin();
    }
    
    
}
